version: 2

services:
  - type: web
    name: telegram-bot-scraper
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    autoDeploy: true
    disk:
      name: tmp
      mountPath: /tmp
      sizeGB: 1
    envVars:
      - key: PORT
        value: 8000
      - key: PYTHON_UNBUFFERED
        value: 1
      - key: TZ
        value: America/Merida
